# ---

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glossary-server
    entrypoint: python server.py
    ports:
      - "50051:50051"

  test-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glossary-test-client
    entrypoint: python test_client.py
    depends_on:
      - server
    environment:
      SERVER_URL: "server:50051"
